'''
DATA
'''
# # Majors
majors = ("Aerospace Engineering, B.S.", "Agribusiness and Food Industry Management, B.S.", "Agricultural Business, B.S.", "Agricultural Communication, B.S.", "Agricultural Science, B.S.", "Agricultural Systems Management, B.S.", "Animal Health Science, B.S.", 
                  "Animal Science, B.S.", "Anthropology And Geography, B.S.", "Anthropology B.A.", "Apparel Merchandising and Management, B.S.", "Architectural Engineering, B.S.", "Architecture, B. Architecture", "Architecture, B.A.", "Art And Design, B. Fine Arts", "Art B.A.", 
                  "Art B.F.A.", "Art History, B.A.", "Biochemistry, B.S.", "Biological Sciences, B.S.", "Biology B.S.", "Biomedical Engineering, B.S.", "Bioresource And Agricultural Engineering, B.S.", "Biotechnology, B.S.", "Botany B.S.", "Business Administration, B.S.", "Business Administration B.S.", 
                  "Chemical Engineering, B.S.", "Chemistry, B.S.", "Chemistry, B.A.", "Chemistry B.S.", "Child Development, B.S.", "Child Development & Family Relations B.A.", "City And Regional Planning, B.S.", "Civil Engineering, B.S.", "Communication B.A.", "Communication Studies, B.A.", 
                  "Comparative Ethnic Studies, B.A.", "Computer Engineering, B.S.", "Computer Science, B.S.", "Computer Science and Engineering, B.S.", "Construction Engineering and Management, B.S.", "Construction Management, B.S.", "Criminology and Justice Studies B.A.", "Critical Race, Gender & Sexuality Studies B.A.", "Dairy Science, B.S.", 
                  "Dance Studies [Interdisciplinary Studies B.A - Dance Studies Concentration]", "Early Childhood Studies, B.A.", "Economics, B.S.", "Economics B.A.", "Electrical Engineering, B.S.", "Electromechanical Systems Engineering Technology, B.S.", "Electronic Systems Engineering Technology, B.S.", "English, B.A.", "English B.A.", "Environmental Biology, B.S.", 
                  "Environmental Earth And Soil Science, B.S.", "Environmental Engineering, B.S.", "Environmental Management And Protection, B.S.", "Environmental Resource Engineering B.S.", "Environmental Science & Management B.S.", "Environmental Studies B.A.", "Facilities Engineering Technology, B.S.", 
                  "Fisheries Biology B.S.", "Food Science, B.S.", "Food Science and Technology, B.S.", "Forest And Fire Sciences, B.S.", "Forestry B.S.", "French & Francophone Studies B.A.", "Gender, Ethnicity and Multicultural Studies, B.A.", "General Engineering, B.S.", "Geography B.A.", "Geography B.S.", "Geology B.A.", 
                  "Geology B.S.", "Global Studies and Maritime Affairs, B.A.", "Graphic Communication, B.S.", "History, B.A.", "History B.A.", "Hospitality Management, B.S.", "Industrial Engineering, B.S.", "Industrial Technology And Packaging, B.S.", "International Studies B.A.", "Journalism, B.S.", "Journalism B.A.", 
                  "Kinesiology, B.S.", "Kinesiology B.S.", "Landscape Architecture, B.S.", "Landscape Architecture, B.L.A.", "Leadership Studies [Interdisciplinary Studies B.A. - Leadership Studies Concentration]", "Liberal Arts And Engineering Studies, B.A.", "Liberal Studies, B.S.", "Liberal Studies B.A.", "Manufacturing Engineering, B.S.", 
                  "Marine Engineering Technology, B.S.", "Marine Sciences, B.S.", "Marine Transportation, B.S.", "Materials Engineering, B.S.", "Mathematics, B.S", "Mathematics B.A.", "Mathematics B.S.", "Mechanical Engineering, B.S.", "Microbiology, B.S.", "Music, B.A.", "Music B.A.", "Music B.M.", "Music B.S.", 
                  "Native American Studies B.A.", "Nursing B.S.N. (RN-BSN)", "Nutrition, B.S.", "Oceanography B.S.", "Philosophy, B.A.", "Philosophy B.A.", "Physical Science B.A.", "Physics, B.A.", "Physics, B.S.", "Plant Science, B.S.", "Plant Sciences, B.S.", "Political Science, B.A.", "Political Science, B.S.", 
                  "Political Science B.A.", "Psychology, B.S.", "Psychology B.A.", "Public Health, B.S.", "Rangeland Resource Science B.S.", "Recreation, Parks And Tourism Administration", "Recreation Administration B.A.", "Religious Studies B.A.", "Science, Technology, and Society, B.A.", "Social Work B.A.", 
                  "Sociology, B.A.", "Sociology B.A.", "Software Engineering, B.S.", "Spanish, B.A.", "Spanish B.A.", "Statistics, B.S.", "Theatre Arts, B.A.", "Theatre Arts B.A.", "Urban and Regional Planning, B.S.", "Wildlife B.S.", "Wine And Viticulture, B.S.", "Zoology B.S.")
# Schools
schools = ("Allan Hancock College", "American River College", "Antelope Valley College", "Bakersfield College", "Barstow Community College", "Berkeley City College", "Butte College", "Cabrillo College", "Canada College", "Cerritos College", "Cerro Coso Community College", "Chabot College", "Chaffey College", 
           "Citrus College", "City College of San Francisco", "Clovis Community College", "Coalinga College", "Coastline Community College", "College of Alameda", "College of Marin", "College of San Mateo", "College of the Canyons", "College of the Desert", "College of the Redwoods", "College of the Sequoias", 
           "College of the Siskiyous", "Columbia College", "Compton College", "Compton Community College", "Contra Costa College", "Copper Mountain College", "Cosumnes River College", "Crafton Hills College", "Cuesta College", "Cuyamaca College", "Cypress College", "De Anza College", "Diablo Valley College", "East Los Angeles College", 
           "El Camino College", "Evergreen Valley College", "Feather River College", "Folsom Lake College", "Foothill College", "Fresno City College", "Fullerton College", "Gavilan College", "Glendale Community College", "Golden West College", "Grossmont College", "Hartnell College", "Imperial Valley College", "Irvine Valley College", 
           "Kings River College", "Lake Tahoe Community College", "Laney College", "Las Positas College", "Lassen Community College", "Lemoore College", "Long Beach City College", "Los Angeles City College", "Los Angeles Harbor College", "Los Angeles Mission College", "Los Angeles Pierce College", "Los Angeles Southwest College", 
           "Los Angeles Trade Technical College", "Los Angeles Valley College", "Los Medanos College", "Madera Community College", "Mendocino College", "Merced College", "Merritt College", "MiraCosta College", "Mission College", "Modesto Junior College", "Monterey Peninsula College", "Moorpark College", "Moreno Valley College", 
           "Mount San Antonio College", "Mt. San Jacinto College", "Napa Valley College", "Norco College", "Ohlone College", "Orange Coast College", "Oxnard College", "Palo Verde College", "Palomar College", "Pasadena City College", "Porterville College", "Rancho Santiago College", "Reedley College", "Rio Hondo College", 
           "Riverside City College", "Sacramento City College", "Saddleback College", "San Bernardino Valley College", "San Diego City College", "San Diego Mesa College", "San Diego Miramar College", "San Joaquin Delta College", "San Jose City College", "Santa Ana College", "Santa Barbara City College", "Santa Monica College", 
           "Santa Rosa Junior College", "Santiago Canyon College", "Shasta College", "Sierra College", "Skyline College", "Solano Community College", "Southwestern College", "Taft College", "Ventura College", "Victor Valley College", "Vista Community College", "West Hills College Coalinga", "West Hills College Lemoore", 
           "West Los Angeles College", "West Valley College", "Woodland Community College", "Yuba College", "California Maritime Academy", "California Polytechnic University, Humboldt", "California Polytechnic University, Pomona", "California Polytechnic University, San Luis Obispo", "California State University, Bakersfield", 
           "California State University, Channel Islands", "California State University, Chico", "California State University, Dominguez Hills", "California State University, East Bay", "California State University, Fresno", "California State University, Fullerton","California State University, Hayward", "California State University, Long Beach", 
           "California State University, Los Angeles", "California State University, Maritime Academy", "California State University, Monterey Bay", "California State University, Northridge", "California State University, Sacramento", "California State University, San Bernardino", "California State University, San Marcos", 
           "California State University, Stanislaus", "Humboldt State University", "San Diego State University","San Francisco State University, San Jose State University", "Sonoma State University","University of California, Berkeley", "University of California, Davis", "University of California, Irvine", "University of California, Los Angeles", 
           "University of California, Merced", "University of California, Riverside", "University of California, San Diego", "University of California, Santa Barbara", "University of California, Santa Cruz", "California Baptist University, California Lutheran University", "Charles R. Drew University of Medicine and Science", 
           "Concordia University Irvine", "Dominican University of California", "Fresno Pacific University", "Humphreys University", "Laguna College of Art + Design", "Los Angeles Pacific University", "Loyola Marymount University", "Menlo College", "Mount Saint Mary's University Los Angeles", "National University", "Notre Dame de Namur University",
           "Palo Alto University", "Pepperdine University", "Reach University", "Saint Mary's College of California", "Samuel Merritt University", "Santa Clara University", "Simpson University", "Touro University Worldwide", "University of La Verne", "University of Redlands", "University of the Pacific", "University of the West", "Whittier College")
